version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sryoss-container
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules